// =============================================================================
//    Copyright (c) 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
// =============================================================================
//! Bounded, I/O-free plans for finite resource-limit probes.

/// Maximum payload allocated by one contract limit probe.
pub(crate) const MAX_PROBE_BYTES: u64 = 64 * 1024;
/// Maximum entries generated by one listing probe.
pub(crate) const MAX_PROBE_ENTRIES: u64 = 64;

/// Returns the boundary value and its checked successor when within budget.
pub(crate) const fn bounded_successor(
    maximum: u64,
    budget: u64,
) -> Option<(u64, u64)> {
    if maximum >= budget {
        return None;
    }
    match maximum.checked_add(1) {
        Some(successor) if successor <= budget => Some((maximum, successor)),
        _ => None,
    }
}

/// Plans a finite limit probe while keeping allocations within the testkit
/// budget. Non-finite declarations are intentionally left unprobed.
pub(crate) const fn finite_probe(
    limit: qubit_fs::metadata::FileSystemLimit,
    budget: u64,
) -> Option<(u64, u64)> {
    match limit {
        qubit_fs::metadata::FileSystemLimit::Maximum(maximum) => {
            bounded_successor(maximum, budget)
        }
        qubit_fs::metadata::FileSystemLimit::Unknown
        | qubit_fs::metadata::FileSystemLimit::NotApplicable
        | qubit_fs::metadata::FileSystemLimit::Unbounded => None,
    }
}

/// Clamps a listing page hint to the testkit's bounded request budget.
pub(crate) const fn clamp_page_hint(requested: u64) -> u64 {
    if requested > MAX_PROBE_ENTRIES {
        MAX_PROBE_ENTRIES
    } else {
        requested
    }
}
